name : Node.js CI

on:
  push:
    branches : [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{matrix.node-version}}
      - name: Install and Build 
        run: yarn && yarn build && yarn export
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages 
          FOLDER: out
          CLEAN: true